# Server configuration
recipe: fedavg
n_clients: 4 
client_list: [6, 5, 2, 1] # only 4 largest sites
num_rounds: 50
client_script: "client.py"
client_python_command: "/home/wenytang/nvflare_example/venv/bin/python -u"
workdir: "/home/wenytang/nvflare_example/new_input/federated_runs/fed_training_live" # working directory to save logs and models

# Client configuration
batch_size: 128
learning_rate: 0.0001
client_config_path: "/home/wenytang/nvflare_example/new_input/client_config.yml"

# Data configuration
train_dataset_path: "/mnt/c/Data/EMBED/embed_grouped/train/original"
test_dataset_path: "/mnt/c/Data/EMBED/embed_grouped/test"
meta_data_path: "/mnt/c/Data/EMBED/embed_grouped/tables/legacy_metadata.csv"


# Model configuration
pretrained: false
pretrained_model_path: ""
# model:
#   name: 'ViT'
#   in_channels: 1
#   img_size: 1024
#   patch_size: 32
#   num_layers: 12
#   num_heads: 8
#   hidden_size: 768
#   mlp_dim: 3072
#   dropout_rate: 0
#   proj_type: 'conv'
#   classification: True
#   num_classes: 2
#   pos_embed_type: 'learnable'
# #   spatial_dims: 2
model:
  name: 'ConvNeXtTiny'
  # name: 'ConvNeXtSmall'
  # name: 'ConvNeXtBase'
  num_classes: 2
  pretrained: true
  dropout: 0.5
# model:
#   name: 'SimpleNetwork'
