# HPC smoke-test configuration for centralized training.
# Use the following path for embed data on hpc
data_csv: "/N/u/wenytang/Quartz/embed_data/cleaned_data_points.csv"
cleaned_data_root: "/N/slate/wenytang/embed_cleaned"
workdir: "./centralized_runs/hpc_smoke_cpu_persistent"

splits:
  train: "train"
  validation: "validation"
  test: "test"

seed: 0
dataset: "PersistentDataset"
cache_dir: ./centralized_runs/cache/convnext_256_ras_scale_v1
cache_rate: 1

dataloader:
  batch_size: 128
  num_workers: 10
  shuffle: true
  pin_memory: false

epochs: 2
val_interval: 1
save_metric: "balanced_accuracy"

differential_privacy:
  enabled: false
  accountant: "prv"
  secure_mode: false
  mode: "noise_multiplier"
  noise_multiplier: 1.0
  target_epsilon: null
  target_delta: null
  max_grad_norm: 1.0
  poisson_sampling: true
  clipping: "flat"
  grad_sample_mode: "hooks"
  fix_modules: true

optimizer:
  name: "Adam"
  freeze_backbone: false
  lr_backbone: 0.00001
  lr_finetune: 0.0001
  betas: [0.9, 0.999]
  epsilon: 0.00000008
  weight_decay: 0.00005

loss:
  name: "CrossEntropyLoss"
  label_smoothing: 0.1
  class_weights: true

model:
  name: "ConvNeXtTiny"
  num_classes: 2
  pretrained: true
  dropout: 0.5

train_transforms:
  LoadImaged_im:
    keys: ["image"]
    ensure_channel_first: true
  ScaleIntensityd:
    keys: ["image"]
  Orientationd:
    keys: ["image"]
    axcodes: "RAS"
    as_closest_canonical: true
  ResizeWithPadOrCropd:
    keys: ["image"]
    spatial_size: [256, 256]
  RandFlipd_x:
    keys: ["image"]
    prob: 0.2
    spatial_axis: 0
  RandFlipd_y:
    keys: ["image"]
    prob: 0.2
    spatial_axis: 1
  RandRotated:
    keys: ["image"]
    prob: 0.2
    range_x: [-0.8, 0.8]
    range_y: [-0.8, 0.8]
    mode: "bilinear"
  RandAffined:
    keys: ["image"]
    prob: 0.2
    rotate_range: [0.2]
    scale_range: [0.2]
    mode: "bilinear"

eval_transforms:
  LoadImaged_im:
    keys: ["image"]
    ensure_channel_first: true
  ScaleIntensityd:
    keys: ["image"]
  Orientationd:
    keys: ["image"]
    axcodes: "RAS"
    as_closest_canonical: true
  ResizeWithPadOrCropd:
    keys: ["image"]
    spatial_size: [256, 256]
